// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEkHbNIaI1Y9en3Emd7C9oNAVtOeVNfww',
    appId: '1:224047581745:android:6d4429ad039e49049ca310',
    messagingSenderId: '224047581745',
    projectId: 'gemination-bbecc',
    storageBucket: 'gemination-bbecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmDsZNClt3A1Lk6aW9uCP1KUJ46ULihu8',
    appId: '1:224047581745:ios:1d4913fed44c52209ca310',
    messagingSenderId: '224047581745',
    projectId: 'gemination-bbecc',
    storageBucket: 'gemination-bbecc.firebasestorage.app',
    androidClientId: '224047581745-6b6fimc9j6u70q8pabt55touftssnss1.apps.googleusercontent.com',
    iosClientId: '224047581745-aha0t7p9rq1s1moga0mjd3l4drfghl4l.apps.googleusercontent.com',
    iosBundleId: 'com.surakshaflow.mobile',
  );
}
